<?php

return [
    // [
    //     'name' => 'wx_appid',
    //     'title' => '小程序appid',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'wxa7fdd8a22955a7fb',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写小程序appid',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'wx_secret',
    //     'title' => '小程序AppSecret',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => '41258ed573bfce101e787fc85179503b',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写小程序AppSecret',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'driver_wx_appid',
    //     'title' => '司机端appid',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'wx1dc3cc089b330163',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写司机端appid',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'driver_wx_secret',
    //     'title' => '司机端AppSecret',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'd8c8ba1a647072eeb0a967d3454d9269',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写司机端AppSecret',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'user_wx_appid',
    //     'title' => '乘客端appid',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'wx1dc3cc089b330163',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写乘客端appid',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'user_wx_secret',
    //     'title' => '乘客端AppSecret',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'd8c8ba1a647072eeb0a967d3454d9269',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写乘客端AppSecret',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'user_alipay_app_id',
    //     'title' => '乘客端app_id',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => '2021001185646266',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写乘客端appid',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'user_alipay_ali_public_key',
    //     'title' => '乘客端支付宝公钥',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtb1cIhJWMjvk5nrH6RQuH9gJmhFrAnxkl/lm0tQXrAIFh1iSdcZmVkcpf9K+OE4ioTHwkHys1dMbdGUAJq8AvWAtQ0cmzbJ+34aTmVTSrGpIugXzZB5TMO66BbHLVemlaYePde0IzeUOmr9v2QyW5iY59iKEUXBpG6lknx9sO/3AZFy+3WDDnbBzlrTa3XHVMJhliR5zjT9Q0GTu6t0439ElDpwJdLmASPOdU9gGTvLagg5or2KpA9BENRpCxd5N2N5lZSHcdscxG+eIGyAmYJ0XwvarOQziUV3BPHdCN1Ks1r7w3OrpFbI8paBSDB3y7OOGYjj8DRrLZVZ80mWN0wIDAQAB',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写乘客端支付宝公钥',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'user_alipay_private_key',
    //     'title' => '乘客端支付宝私钥',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'MIIEowIBAAKCAQEAowsuABiDy6ijaAplvgmcpDQrumUmseZdivZdgMNgXqXIO+mT0eGSQDfc0rx06fZqkDHNIYNaTGKpCfKN2fqS7sjgALYuiBrznKvHkvadcs6YJSp/lkgdXJwzyxO+is4MsBVXID1Ir+wJ3zZqRN2fktro5O6VyJ+oG2YQIFdgm5joC1mt0Nxeg3bXxB4g6GWi+K/7zH57s2HYLTO+Ux7xOrEzCgc7w6kz1DegIsSfbbpMFB+mqUtcY1IJ2lwkICrHuyWGXvUD+RQVP9zAxhCQMZ6gcnzz2gTa9I3F7mAAd4+YJXO8vbqCC3ci0bvbGWxSIkHa/ilCjCRggTg11vBdrQIDAQABAoIBAHQ8SiUjVQJiTWykzPf4XkXqM6qE5ls5wkKJdQuRPij7w46C7TFZwSwrJzDNzgPl+v6lonpb7Io8ZAqFc3+NVicJ6jhXqUC7BiYRiQxK6OCqTGlirOb0rooRihMjFlpan00BScXgKuvQORF697P01AicLCDZvsryl6RA1QpZgLQr3+22goChXnC3TlytFfCvFnNRfkwkj9RGLqw0vw87wx8hbJrW/k4be9JA8EHym4dNWpt93QVNvWhDjojp7bssbWlwNkP/rdN1GcPi5PC9C0dIEZEssox6cbZlLfntbtVUl8tHB1/J1WTTk61ZkNtyfrOJ7+apQlexeChQP3lqQPkCgYEA39T1eComULr9oujdUMWdmNZmmWYtgx0lc3LLrKUdBccW2EjJe6h6XqJXiLPBI12INWhxaPqEVaJdserUjz9JQtSRKjXsmgUiC3HHefthncyCMgkOJ/Q0Y4nckJWw74tdUWU5ArupmKB7G8JYAJw9cI506m8wTMbszosmn4zsmycCgYEAunnAI4I9/5HNn9UyOVaN67jYS6FKNbgpxRgxJj+yBRQWE6IWrWTj+eKWQDSDQ0nBZ0mF+hLg6tIWksIJ4oCAKURaWQDLNkRG0/X33AwxaCyoIr986ZawYQ6U6WMvbdXEgrG6FPsDXyQIxPyUHQBLG/mDY8WuffIU+aau/sTIlQsCgYEArDuVKwLb+tD4LGwdKHL3gsyvpCgwqyw5Ti2uNcnTnEeG96SCjUml573pt0ICQvFMxzP32Hy0aaSHjkkRiKx89hTVIvLdfeKnQMEralyZz6+3G0NGhk3uJg3GD+dvf9PwWZqXFNhMdyo9sK2Jw+Z1jG/B3UbzlpCXVZNThAAPbI8CgYAts7UxfrQvNM7Og3PhtaLmyNDKCGelrtMd6QXyt92rfPbELQ+dw4JUNgJZDgW1shfidpSNa58QLhk2MrQ1fQTsGEKEWbt0O1uYi0oJ9jsNqxQyH/g/T50+zFIWuSZgpumYlnJivfpfkPdNQBIU4YOHAaoAA+z2FSSq4v00l4oJbQKBgAskWMWmw/zHjCCI3YPFZNOoBDZJopnTxrVPTFqJlV9gwcQx7dAqyJXXZrqE1lB4gYPbu/Lc0BywHHkvhOXuaV0ykQw26AztlIHYNUZewfDZVEH2ERAViRiucgkmNTdwPft2aPVDMH1Ux4EqVVfAvIqRsIAu6BKRN78V+3YlXc6d',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写乘客端支付宝私钥',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'mch_id',
    //     'title' => '商户号',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => '1621729151',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写商户号',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'key',
    //     'title' => '支付key',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'c651fcbe10fe8146ed4adfbbd1b377d7',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写支付key',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    [
        'name' => 'platform_service_fee_250',
        'title' => '250元以上平台服务费（%）',
        'type' => 'number',
        'content' => [],
        'value' => '16',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'platform_service_fee_150',
        'title' => '150元以上平台服务费（%）',
        'type' => 'number',
        'content' => [],
        'value' => '14',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'platform_service_fee',
        'title' => '平台服务费（%）',
        'type' => 'number',
        'content' => [],
        'value' => '12',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
      // 保险费
        'name' => 'insurance_fee',
        'title' => '保险费（元/每单）',
        'type' => 'number',
        'content' => [],
        'value' => '2',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'restrict_service_fee',
        'title' => '服务费欠费上限/元',
        'type' => 'number',
        'content' => [],
        'value' => '200',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    // [
    //     'name' => 'withdraw_rate',
    //     'title' => '提现手续费（%）',
    //     'type' => 'number',
    //     'content' => [],
    //     'value' => '1',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'withdraw_min',
    //     'title' => '单笔最低提现',
    //     'type' => 'number',
    //     'content' => [],
    //     'value' => '10',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'withdraw_max',
    //     'title' => '单笔最高提现',
    //     'type' => 'number',
    //     'content' => [],
    //     'value' => '10000',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    [
        'name' => 'mileage',
        'title' => '起步里程/km',
        'type' => 'number',
        'content' => [],
        'value' => '5',
        'rule' => 'required',
        'msg' => '',
        'tip' => '例：填写5表示5公里内只收取当前时段基础价',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'base_price',
        'title' => '白天基础价/元',
        'type' => 'number',
        'content' => [],
        'value' => '30',
        'rule' => 'required',
        'msg' => '',
        'tip' => '白天基础价',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'night_base_price',
        'title' => '夜晚基础价/元',
        'type' => 'number',
        'content' => [],
        'value' => '40',
        'rule' => 'required',
        'msg' => '',
        'tip' => '夜晚基础价',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'kilometer_price',
        'title' => '每公里价格/元',
        'type' => 'number',
        'content' => [],
        'value' => '5',
        'rule' => 'required',
        'msg' => '',
        'tip' => '超出基础价外每公里费用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'excision_start_time',
        'title' => '白天夜晚分割开始时间/时',
        'type' => 'number',
        'content' => [],
        'value' => '7',
        'rule' => 'required',
        'msg' => '',
        'tip' => '填写6表示06点后以白天基础价为准',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'excision_time',
        'title' => '白天夜晚分割结束时间/时',
        'type' => 'number',
        'content' => [],
        'value' => '24',
        'rule' => 'required',
        'msg' => '',
        'tip' => '填写22表示22点前以白天基础价为准',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'timeout',
        'title' => '用户超时时间/分钟',
        'type' => 'number',
        'content' => [],
        'value' => '5',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'timeout_price',
        'title' => '用户超时后费用/每分钟（元）',
        'type' => 'number',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    // [
    //     'name' => 'phone',
    //     'title' => '客服电话',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => '010-11111111',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写客服电话',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'worktime',
    //     'title' => '工作时间',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => '08:00-23:00',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写客服电话',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'email',
    //     'title' => '客服邮箱',
    //     'type' => 'string',
    //     'content' => [],
    //     'value' => 'test@test.com',
    //     'rule' => 'required,email',
    //     'msg' => '',
    //     'tip' => '请填写客服邮箱',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    // [
    //     'name' => 'notice',
    //     'title' => '代驾须知',
    //     'type' => 'text',
    //     'value' => '<p>1、5年以上驾龄。</p><p>2、熟悉路道。</p><p>3、必须熟练操作手动挡，自动挡。</p><p>4、年龄在25~55之间。</p><p>5、.上岗前24小时严禁饮酒。</p><p>6、微笑上岗、语音、语速清晰;</p><p>7、仪容仪表(佩戴胸卡、着装、头发、指甲干净整洁、勤洗澡不能有异味);</p><p>8、身体状态(不应带病上岗，保证身体状况良好);</p><p>9、不吃有异味的食品，保持口腔清洁;</p><p>代驾员服务中须携带物品</p><p>①驾驶证、工牌、交通卡(方便出行)</p><p>②手机、充电宝(方便与客户联系，保持电量，音量调到合适档)</p><p>③笔、服务确认单、公司名片</p><p>④防雨具(如下雨，请自备2把，把伞撑开递给客户或帮助客户打伞送至车内)</p><p>⑤准备零钱(1元、 21元、41元、61元)</p><p>⑥其它选带用品(湿纸巾、饮用水、手套、塑料袋)</p>',
    //     'rule' => 'required',
    //     'msg' => '',
    //     'tip' => '请填写代驾须知',
    //     'ok' => '',
    //     'extend' => 'class="form-control editor"',
    // ],
    // [
    //     'name' => 'noticeMobile',
    //     'title' => '订单短信提醒',
    //     'type' => 'text',
    //     'value' => '15096677027,13658836625',
    //     'rule' => '',
    //     'msg' => '',
    //     'tip' => '多个手机号以英文半角逗号（,）间隔',
    //     'ok' => '',
    //     'extend' => '',
    // ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '已默认部分配置，请按照个人需要进行修改',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
