<?php

return [
    [
        'name' => 'platform_service_fee_250',
        'title' => '250元以上平台服务费（%）',
        'type' => 'number',
        'content' => [],
        'value' => '16',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'platform_service_fee_150',
        'title' => '150元以上平台服务费（%）',
        'type' => 'number',
        'content' => [],
        'value' => '14',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'platform_service_fee',
        'title' => '平台服务费（%）',
        'type' => 'number',
        'content' => [],
        'value' => '12',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'insurance_fee',
        'title' => '保险费（元/每单）',
        'type' => 'number',
        'content' => [],
        'value' => '2',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'restrict_service_fee',
        'title' => '服务费欠费上限/元',
        'type' => 'number',
        'content' => [],
        'value' => '200',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'mileage',
        'title' => '起步里程/km',
        'type' => 'number',
        'content' => [],
        'value' => '5',
        'rule' => 'required',
        'msg' => '',
        'tip' => '例：填写5表示5公里内只收取当前时段基础价',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'base_price',
        'title' => '白天基础价/元',
        'type' => 'number',
        'content' => [],
        'value' => '30',
        'rule' => 'required',
        'msg' => '',
        'tip' => '白天基础价',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'night_base_price',
        'title' => '夜晚基础价/元',
        'type' => 'number',
        'content' => [],
        'value' => '40',
        'rule' => 'required',
        'msg' => '',
        'tip' => '夜晚基础价',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'kilometer_price',
        'title' => '每公里价格/元',
        'type' => 'number',
        'content' => [],
        'value' => '5',
        'rule' => 'required',
        'msg' => '',
        'tip' => '超出基础价外每公里费用',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'excision_start_time',
        'title' => '白天夜晚分割开始时间/时',
        'type' => 'number',
        'content' => [],
        'value' => '7',
        'rule' => 'required',
        'msg' => '',
        'tip' => '填写6表示06点后以白天基础价为准',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'excision_time',
        'title' => '白天夜晚分割结束时间/时',
        'type' => 'number',
        'content' => [],
        'value' => '24',
        'rule' => 'required',
        'msg' => '',
        'tip' => '填写22表示22点前以白天基础价为准',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'timeout',
        'title' => '用户超时时间/分钟',
        'type' => 'number',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'timeout_price',
        'title' => '用户超时后费用/每分钟（元）',
        'type' => 'number',
        'content' => [],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => 'string',
        'content' => [],
        'value' => '已默认部分配置，请按照个人需要进行修改',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
