<?php

return [
    [
        'name' => 'maptype',
        'title' => '默认地图类型',
        'type' => 'radio',
        'content' => [
            'baidu' => '百度地图',
            'amap' => '高德地图',
            'tencent' => '腾讯地图',
        ],
        'value' => 'amap',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'location',
        'title' => '默认检索城市',
        'type' => 'string',
        'content' => [],
        'value' => '北京',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'zoom',
        'title' => '默认缩放级别',
        'type' => 'string',
        'content' => [],
        'value' => '12',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'lat',
        'title' => '默认Lat',
        'type' => 'string',
        'content' => [],
        'value' => '39.919990',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'lng',
        'title' => '默认Lng',
        'type' => 'string',
        'content' => [],
        'value' => '116.456270',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'baidukey',
        'title' => '百度地图KEY',
        'type' => 'string',
        'content' => [],
        'value' => 'WrOXhGtpfuuvC0L7FejmpVF23cUGiHnI',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'amapkey',
        'title' => '高德地图KEY',
        'type' => 'string',
        'content' => [],
        'value' => '933d834b0ed50dfce22525afc12a94b9',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'tencentkey',
        'title' => '腾讯地图KEY',
        'type' => 'string',
        'content' => [],
        'value' => 'JVXBZ-RAUR6-7FNS6-MIY3U-AQQVH-XEF6K',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => '__tips__',
        'title' => '温馨提示',
        'type' => '',
        'content' => [],
        'value' => '请先申请对应地图的Key，配置后再使用',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => 'alert-danger-light',
    ],
];
